# Generated by Django 2.2.12 on 2020-05-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf', '0002_add_page_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagenode',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='pagenode',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='pagenode',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
